org.gradle.jvmargs=-Xmx10G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version=21.1.197
loader_version_range=[1,)

## Mod Properties
mod_id=mogruleconomy
mod_name=Mogrul Economy
mod_license=CC A-NC-ND 4.0
mod_version=0.1-1.21.1
mod_group_id=net.mogrul.factions
mod_authors=Mogrul
mod_description=A simple server-side economy mod with a variety of components.
