# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.7
parchment_mappings_version=2025.07.18
minecraft_version=1.21.7
minecraft_version_range=[1.21.7]
neo_version=21.7.25-beta

mod_id=mogruleconomy
mod_name=Mogrul Economy
mod_license=CC A-NC-ND 4.0
mod_version=0.35-1.21.7
mod_group_id=net.mogrul.economy
mod_authors=Mogrul
mod_description=A simple server-side economy mod with a variety of components.